version: "3.11.1"
services:
  postgres:
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
  myapp:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - postgres
